[[llama_cpp]]
arch = "aarch64"
git-tree-sha1 = "9d772b8ba4c93e20c3420fffb3dc58955577fc14"
os = "macos"

    [[llama_cpp.download]]
    sha256 = "5d62fd31204630af52acfa9a31eae8959dcaa600dd4318c7cd1008c160a6504b"
    url = "https://github.com/JuliaBinaryWrappers/llama_cpp_jll.jl/releases/download/llama_cpp-v0.0.13+0/llama_cpp.v0.0.13.aarch64-apple-darwin.tar.gz"
[[llama_cpp]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "204f2f28e8324bde3bf4be90e91d0870ff71ccd3"
libc = "glibc"
os = "linux"

    [[llama_cpp.download]]
    sha256 = "9187e62b2fe05162783da2669fca3a6a6196fc49ebea7764c1480eb10ae548ba"
    url = "https://github.com/JuliaBinaryWrappers/llama_cpp_jll.jl/releases/download/llama_cpp-v0.0.13+0/llama_cpp.v0.0.13.aarch64-linux-gnu-cxx03.tar.gz"
[[llama_cpp]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d7e84ae4a6c3e1946e389e5ebea7cf395e158c96"
libc = "glibc"
os = "linux"

    [[llama_cpp.download]]
    sha256 = "cd24f50ea56eb375f1c6fcd203750cb7d951804c75e4936681bb4d0e1d62b1f0"
    url = "https://github.com/JuliaBinaryWrappers/llama_cpp_jll.jl/releases/download/llama_cpp-v0.0.13+0/llama_cpp.v0.0.13.aarch64-linux-gnu-cxx11.tar.gz"
[[llama_cpp]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f7e69dfcb2b9970313b9f75e76af66781cbffa60"
libc = "musl"
os = "linux"

    [[llama_cpp.download]]
    sha256 = "f95b375a1b0fb5c25fe31ed23f4bd9a924e50e3f3a53eac51f3de2301ecf4654"
    url = "https://github.com/JuliaBinaryWrappers/llama_cpp_jll.jl/releases/download/llama_cpp-v0.0.13+0/llama_cpp.v0.0.13.aarch64-linux-musl-cxx03.tar.gz"
[[llama_cpp]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6db8700085557440f7809b7df4b03fa96e424b3f"
libc = "musl"
os = "linux"

    [[llama_cpp.download]]
    sha256 = "74ab65aa0b040cf5c041401a221c642c0c6288a1943c1cb1d7b231eb514dcb92"
    url = "https://github.com/JuliaBinaryWrappers/llama_cpp_jll.jl/releases/download/llama_cpp-v0.0.13+0/llama_cpp.v0.0.13.aarch64-linux-musl-cxx11.tar.gz"
[[llama_cpp]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "4ef974989708ecc34cbbb78b301a5fccb913fc23"
libc = "glibc"
os = "linux"

    [[llama_cpp.download]]
    sha256 = "10e52a3a2fac621f91f6585593114137e801f348e69850237c6c40ed4302e2e9"
    url = "https://github.com/JuliaBinaryWrappers/llama_cpp_jll.jl/releases/download/llama_cpp-v0.0.13+0/llama_cpp.v0.0.13.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[llama_cpp]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1879a36c2c940e042f81afe33a48715fb2c619fd"
libc = "glibc"
os = "linux"

    [[llama_cpp.download]]
    sha256 = "07e1c5acccf1f2387a5dab8d1e9dd281bad2c174aafccbce24e21184d78a41c8"
    url = "https://github.com/JuliaBinaryWrappers/llama_cpp_jll.jl/releases/download/llama_cpp-v0.0.13+0/llama_cpp.v0.0.13.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[llama_cpp]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "00c9db0fe6d69756ea4ad3df8542fc08c3fab634"
libc = "musl"
os = "linux"

    [[llama_cpp.download]]
    sha256 = "73f1d0ea2034bd7f1f4e05e13361b1ce2f04d58a8f0cd4fe7b68f9a27063d1f7"
    url = "https://github.com/JuliaBinaryWrappers/llama_cpp_jll.jl/releases/download/llama_cpp-v0.0.13+0/llama_cpp.v0.0.13.armv6l-linux-musleabihf-cxx03.tar.gz"
[[llama_cpp]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a9b198cc2f1538ffdc4a589f5edc14c392f1aa2a"
libc = "musl"
os = "linux"

    [[llama_cpp.download]]
    sha256 = "073e970e06f4a49df4ed03afd2ea17340477cac3ae5174b85f2b0345ef032427"
    url = "https://github.com/JuliaBinaryWrappers/llama_cpp_jll.jl/releases/download/llama_cpp-v0.0.13+0/llama_cpp.v0.0.13.armv6l-linux-musleabihf-cxx11.tar.gz"
[[llama_cpp]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ce857a457c5a11d98433e25ef883ffe70f3eb303"
libc = "glibc"
os = "linux"

    [[llama_cpp.download]]
    sha256 = "0f00a0eada097af24836a40f4aedd507a9eff322e3d3aadd5a24d1cb636bfb51"
    url = "https://github.com/JuliaBinaryWrappers/llama_cpp_jll.jl/releases/download/llama_cpp-v0.0.13+0/llama_cpp.v0.0.13.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[llama_cpp]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "db9a5929081ba3361f68c9257cfe50b1b3c5cdfd"
libc = "glibc"
os = "linux"

    [[llama_cpp.download]]
    sha256 = "1a942d41beeff82aa369ea0864b3c5886eacb377cba99aef869c4a2d05a736b4"
    url = "https://github.com/JuliaBinaryWrappers/llama_cpp_jll.jl/releases/download/llama_cpp-v0.0.13+0/llama_cpp.v0.0.13.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[llama_cpp]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "fc573abb2a2adeb9ee252ae5d2f498a37a11e87b"
libc = "musl"
os = "linux"

    [[llama_cpp.download]]
    sha256 = "258bff849ade58dcdc2872829c2e1138ede68c1af58d13699e3acfaec7edf06f"
    url = "https://github.com/JuliaBinaryWrappers/llama_cpp_jll.jl/releases/download/llama_cpp-v0.0.13+0/llama_cpp.v0.0.13.armv7l-linux-musleabihf-cxx03.tar.gz"
[[llama_cpp]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e8a5b7685dea2f7ac19267b82c36b3d94de437c8"
libc = "musl"
os = "linux"

    [[llama_cpp.download]]
    sha256 = "10052f0927caa19b6c6cadbfcfcdee82a93f5d33d95f382095922871ecf02e4e"
    url = "https://github.com/JuliaBinaryWrappers/llama_cpp_jll.jl/releases/download/llama_cpp-v0.0.13+0/llama_cpp.v0.0.13.armv7l-linux-musleabihf-cxx11.tar.gz"
[[llama_cpp]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "62eb53d42b4841818fd6656a672cd5e52acab708"
libc = "glibc"
os = "linux"

    [[llama_cpp.download]]
    sha256 = "fa81796013a4271c541062ede5a91aca4d4e6e9bb6a9948ce99408f76696223c"
    url = "https://github.com/JuliaBinaryWrappers/llama_cpp_jll.jl/releases/download/llama_cpp-v0.0.13+0/llama_cpp.v0.0.13.i686-linux-gnu-cxx03.tar.gz"
[[llama_cpp]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "83fe13478a122fd1bdd4670bd4ac893b9350632b"
libc = "glibc"
os = "linux"

    [[llama_cpp.download]]
    sha256 = "9f64a5e6d563bedf2af03db79d215eb195480577f72287a26ba227b85a921257"
    url = "https://github.com/JuliaBinaryWrappers/llama_cpp_jll.jl/releases/download/llama_cpp-v0.0.13+0/llama_cpp.v0.0.13.i686-linux-gnu-cxx11.tar.gz"
[[llama_cpp]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "96a978eea41c30ca36076472c4affc4f6a1a1947"
libc = "musl"
os = "linux"

    [[llama_cpp.download]]
    sha256 = "ffa81de13d37295fc560ae3348d41ed86ef5e250efe01cb80037176943475d3b"
    url = "https://github.com/JuliaBinaryWrappers/llama_cpp_jll.jl/releases/download/llama_cpp-v0.0.13+0/llama_cpp.v0.0.13.i686-linux-musl-cxx03.tar.gz"
[[llama_cpp]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ed799bf5ca4b50100c7297c269dda89b193c0567"
libc = "musl"
os = "linux"

    [[llama_cpp.download]]
    sha256 = "458adadaad37b4deafb80f655ec89eb11584488fe29d21b3e98fa299c1ca05f1"
    url = "https://github.com/JuliaBinaryWrappers/llama_cpp_jll.jl/releases/download/llama_cpp-v0.0.13+0/llama_cpp.v0.0.13.i686-linux-musl-cxx11.tar.gz"
[[llama_cpp]]
arch = "x86_64"
git-tree-sha1 = "c07951d09f191c279a293f37797a4103bd7863a4"
os = "macos"

    [[llama_cpp.download]]
    sha256 = "a914198cfc05961913089592df885bff04ea0c6451bdd071dd52af802f47165f"
    url = "https://github.com/JuliaBinaryWrappers/llama_cpp_jll.jl/releases/download/llama_cpp-v0.0.13+0/llama_cpp.v0.0.13.x86_64-apple-darwin.tar.gz"
[[llama_cpp]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "facd76c7978c25f6c6a099a6ed9196cc3838d9d6"
libc = "glibc"
os = "linux"

    [[llama_cpp.download]]
    sha256 = "20b7642b915cb1f085beef582bdd466f987dddcf046482a3725613ccd3eb69fd"
    url = "https://github.com/JuliaBinaryWrappers/llama_cpp_jll.jl/releases/download/llama_cpp-v0.0.13+0/llama_cpp.v0.0.13.x86_64-linux-gnu-cxx03.tar.gz"
[[llama_cpp]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a4c487762c8f5db50de165051191bf5f347772dd"
libc = "glibc"
os = "linux"

    [[llama_cpp.download]]
    sha256 = "57d41b428fd723f3d627abb3a8eb6fdb7b796bcc060025f900226dcdbe79497f"
    url = "https://github.com/JuliaBinaryWrappers/llama_cpp_jll.jl/releases/download/llama_cpp-v0.0.13+0/llama_cpp.v0.0.13.x86_64-linux-gnu-cxx11.tar.gz"
[[llama_cpp]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "58af90854c676488fd532b0bf2811f424cf78c6e"
libc = "musl"
os = "linux"

    [[llama_cpp.download]]
    sha256 = "3f5d99dd4fa534fb475ad219af31711737fe72c7d5093ee12c15345ce3009504"
    url = "https://github.com/JuliaBinaryWrappers/llama_cpp_jll.jl/releases/download/llama_cpp-v0.0.13+0/llama_cpp.v0.0.13.x86_64-linux-musl-cxx03.tar.gz"
[[llama_cpp]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5e1dc9427f56e7b7d8ea1b34049a8e5c2edaf216"
libc = "musl"
os = "linux"

    [[llama_cpp.download]]
    sha256 = "fa055b4c5081a8f8f6b99fcfcdf06d3905c171c834a82ca04a284478889213ca"
    url = "https://github.com/JuliaBinaryWrappers/llama_cpp_jll.jl/releases/download/llama_cpp-v0.0.13+0/llama_cpp.v0.0.13.x86_64-linux-musl-cxx11.tar.gz"
[[llama_cpp]]
arch = "x86_64"
git-tree-sha1 = "bf866e9ca90e4536039fa7fe871e0a981b0fa2b7"
os = "freebsd"

    [[llama_cpp.download]]
    sha256 = "8892b1064ea23d028ef0739277a7a04eb869100af1e075e1c03c65e9aba4afe1"
    url = "https://github.com/JuliaBinaryWrappers/llama_cpp_jll.jl/releases/download/llama_cpp-v0.0.13+0/llama_cpp.v0.0.13.x86_64-unknown-freebsd.tar.gz"
[[llama_cpp]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a86fbe302b767e487fcfbfaa7e2314369f1ec51c"
os = "windows"

    [[llama_cpp.download]]
    sha256 = "b4c3d936f42b67225908eb6f7039685b84eb5b014b543442e3971341a46e47a5"
    url = "https://github.com/JuliaBinaryWrappers/llama_cpp_jll.jl/releases/download/llama_cpp-v0.0.13+0/llama_cpp.v0.0.13.x86_64-w64-mingw32-cxx03.tar.gz"
[[llama_cpp]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4608c2a279cda2829f498c78800358ca072fef53"
os = "windows"

    [[llama_cpp.download]]
    sha256 = "bb53b34ebf7d4020d7167fb036e311b8e06dd6faa612f38d1a5e6143b84659f3"
    url = "https://github.com/JuliaBinaryWrappers/llama_cpp_jll.jl/releases/download/llama_cpp-v0.0.13+0/llama_cpp.v0.0.13.x86_64-w64-mingw32-cxx11.tar.gz"
