[[llama_cpp]]
arch = "aarch64"
git-tree-sha1 = "3fb4b9ffcd7a3ae5bc8d30f45ca21b7b822d7684"
os = "macos"

    [[llama_cpp.download]]
    sha256 = "81ca563b3549d6e87e8b19173f883bb16ec7b4729e576cdb41b84d496bcd12ad"
    url = "https://github.com/JuliaBinaryWrappers/llama_cpp_jll.jl/releases/download/llama_cpp-v0.0.9+0/llama_cpp.v0.0.9.aarch64-apple-darwin.tar.gz"
[[llama_cpp]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "daaeddda8cf5da2e721248947067ed0cd7083ae8"
libc = "glibc"
os = "linux"

    [[llama_cpp.download]]
    sha256 = "ef34dc06f338ec69d573395a9ae76e1a454c360ddcbf5d4dbcd4e5957c23fab2"
    url = "https://github.com/JuliaBinaryWrappers/llama_cpp_jll.jl/releases/download/llama_cpp-v0.0.9+0/llama_cpp.v0.0.9.aarch64-linux-gnu-cxx03.tar.gz"
[[llama_cpp]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "72d1415c7c5e0ee2a32abedc7af4c0abca24552f"
libc = "glibc"
os = "linux"

    [[llama_cpp.download]]
    sha256 = "169b761a8212e0d889579e82e74b3d8e92908e6f724d3c689ac19bb0959802b8"
    url = "https://github.com/JuliaBinaryWrappers/llama_cpp_jll.jl/releases/download/llama_cpp-v0.0.9+0/llama_cpp.v0.0.9.aarch64-linux-gnu-cxx11.tar.gz"
[[llama_cpp]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "97e92dcdfc5aafcb99548f8da240b03617306514"
libc = "musl"
os = "linux"

    [[llama_cpp.download]]
    sha256 = "9b81153812f5d4a87ce0a9f4231e29942ea83d89e8b7afbe4bf3b177fe43d4c4"
    url = "https://github.com/JuliaBinaryWrappers/llama_cpp_jll.jl/releases/download/llama_cpp-v0.0.9+0/llama_cpp.v0.0.9.aarch64-linux-musl-cxx03.tar.gz"
[[llama_cpp]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b90bec78f7effb73b3bcec0bf52f2b62a86523b6"
libc = "musl"
os = "linux"

    [[llama_cpp.download]]
    sha256 = "54feecbb3d0ab2902cc5281fbecf913d89512a693ff50e691775eb6a433ec021"
    url = "https://github.com/JuliaBinaryWrappers/llama_cpp_jll.jl/releases/download/llama_cpp-v0.0.9+0/llama_cpp.v0.0.9.aarch64-linux-musl-cxx11.tar.gz"
[[llama_cpp]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e4d717a8785db545ed22afb28709252d0d3f612b"
libc = "glibc"
os = "linux"

    [[llama_cpp.download]]
    sha256 = "eb9f0364a98a98978d94ea44282db074eec28e026ff21c3902270ac9b1d44b7d"
    url = "https://github.com/JuliaBinaryWrappers/llama_cpp_jll.jl/releases/download/llama_cpp-v0.0.9+0/llama_cpp.v0.0.9.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[llama_cpp]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e18b2e80b196e6750584c45d8ee7eb0463a91b6f"
libc = "glibc"
os = "linux"

    [[llama_cpp.download]]
    sha256 = "d00edba7f9abf7d663ac2e420c45385e42eb591ea43a343d8d27622d4f4ee960"
    url = "https://github.com/JuliaBinaryWrappers/llama_cpp_jll.jl/releases/download/llama_cpp-v0.0.9+0/llama_cpp.v0.0.9.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[llama_cpp]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "634e75b04ae3cc3c7b8debc27d8ac816d3fe8661"
libc = "musl"
os = "linux"

    [[llama_cpp.download]]
    sha256 = "d7a54ccfbf379241df76596d0dfc6a217c121755baed402d243dc070a6f2cb12"
    url = "https://github.com/JuliaBinaryWrappers/llama_cpp_jll.jl/releases/download/llama_cpp-v0.0.9+0/llama_cpp.v0.0.9.armv6l-linux-musleabihf-cxx03.tar.gz"
[[llama_cpp]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ce4f483c2866155e345927d289ef467209975c00"
libc = "musl"
os = "linux"

    [[llama_cpp.download]]
    sha256 = "b8fbfa027dd7a6591df0abb7f6c9d3eff0541434a2b0edc9f3fc83788728785f"
    url = "https://github.com/JuliaBinaryWrappers/llama_cpp_jll.jl/releases/download/llama_cpp-v0.0.9+0/llama_cpp.v0.0.9.armv6l-linux-musleabihf-cxx11.tar.gz"
[[llama_cpp]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "5d8321bb7797bbf7b369e2cc1ab7884ca6492705"
libc = "glibc"
os = "linux"

    [[llama_cpp.download]]
    sha256 = "41f09c58d01f798c0d9bae9f3a54cea5feece1687cf728169141b9192778f1b4"
    url = "https://github.com/JuliaBinaryWrappers/llama_cpp_jll.jl/releases/download/llama_cpp-v0.0.9+0/llama_cpp.v0.0.9.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[llama_cpp]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6728434ff173aef7263b20fd7d1732da499a87bb"
libc = "glibc"
os = "linux"

    [[llama_cpp.download]]
    sha256 = "d62c93b871178899f9347053094764cd56ea3f355bb709909089aebf6e7fbd96"
    url = "https://github.com/JuliaBinaryWrappers/llama_cpp_jll.jl/releases/download/llama_cpp-v0.0.9+0/llama_cpp.v0.0.9.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[llama_cpp]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "41464d22939084d4369b2fc031a94109c1ac3cae"
libc = "musl"
os = "linux"

    [[llama_cpp.download]]
    sha256 = "507402522a9498be0520c069ac92d630315fdfc9654f86bb0e4b9357aec5798b"
    url = "https://github.com/JuliaBinaryWrappers/llama_cpp_jll.jl/releases/download/llama_cpp-v0.0.9+0/llama_cpp.v0.0.9.armv7l-linux-musleabihf-cxx03.tar.gz"
[[llama_cpp]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "bc3153f6530fd1ddd64aecb5625cd6f24f545828"
libc = "musl"
os = "linux"

    [[llama_cpp.download]]
    sha256 = "16c1c4b623aa984016e8af1a4fade8bab37c11a63d8497ba7400737dbc3c6317"
    url = "https://github.com/JuliaBinaryWrappers/llama_cpp_jll.jl/releases/download/llama_cpp-v0.0.9+0/llama_cpp.v0.0.9.armv7l-linux-musleabihf-cxx11.tar.gz"
[[llama_cpp]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "18d7a5fd18ac7103442b16e5a2d9956811c06a38"
libc = "glibc"
os = "linux"

    [[llama_cpp.download]]
    sha256 = "a4c06bb1b930159f44f8bc5f03c629efbfee82f44abb957a510065a212464a93"
    url = "https://github.com/JuliaBinaryWrappers/llama_cpp_jll.jl/releases/download/llama_cpp-v0.0.9+0/llama_cpp.v0.0.9.i686-linux-gnu-cxx03.tar.gz"
[[llama_cpp]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2842a78bb48192c51cff882949f4d9df501bf93c"
libc = "glibc"
os = "linux"

    [[llama_cpp.download]]
    sha256 = "a267f75ec5e894307809fb1d49f7210aff782d3a33f6c7439da6b968b9dd16c2"
    url = "https://github.com/JuliaBinaryWrappers/llama_cpp_jll.jl/releases/download/llama_cpp-v0.0.9+0/llama_cpp.v0.0.9.i686-linux-gnu-cxx11.tar.gz"
[[llama_cpp]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "cb4c4bbbc562e1f13b5eb3823e0cc4cf61ce139e"
libc = "musl"
os = "linux"

    [[llama_cpp.download]]
    sha256 = "6aa6333d0344aba1abb04ee4162cc57fa03f791f4ce43081d084430ea7b61d5b"
    url = "https://github.com/JuliaBinaryWrappers/llama_cpp_jll.jl/releases/download/llama_cpp-v0.0.9+0/llama_cpp.v0.0.9.i686-linux-musl-cxx03.tar.gz"
[[llama_cpp]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8e28d42490b4e763c48a3f72173a4a1d69da66fe"
libc = "musl"
os = "linux"

    [[llama_cpp.download]]
    sha256 = "de9ce0d072d995493e4f7f43f4822caae9912d2b596ff22d3ea8310cdeb6eb3f"
    url = "https://github.com/JuliaBinaryWrappers/llama_cpp_jll.jl/releases/download/llama_cpp-v0.0.9+0/llama_cpp.v0.0.9.i686-linux-musl-cxx11.tar.gz"
[[llama_cpp]]
arch = "x86_64"
git-tree-sha1 = "833cf8cc1b2de8aae7a4129e5972e0d4b5668a5d"
os = "macos"

    [[llama_cpp.download]]
    sha256 = "2a677ffa79117e98d6f3776f22341e1c437c268f0eaa9b8a5d0cc527d0841b93"
    url = "https://github.com/JuliaBinaryWrappers/llama_cpp_jll.jl/releases/download/llama_cpp-v0.0.9+0/llama_cpp.v0.0.9.x86_64-apple-darwin.tar.gz"
[[llama_cpp]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "aa87f5dad0f76e3f7d8da11068f02bbb0333bbc4"
libc = "glibc"
os = "linux"

    [[llama_cpp.download]]
    sha256 = "bb816dd0cfc92f1dd7d870bd5d678faf34d94ede7e9528271548ad8bfe581c9c"
    url = "https://github.com/JuliaBinaryWrappers/llama_cpp_jll.jl/releases/download/llama_cpp-v0.0.9+0/llama_cpp.v0.0.9.x86_64-linux-gnu-cxx03.tar.gz"
[[llama_cpp]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e21f2ba9490ec6f6d6fb73c3cefdd304103e33b5"
libc = "glibc"
os = "linux"

    [[llama_cpp.download]]
    sha256 = "56b46f630cd24d3e2bea10befedaf1e28496acb067e37f18882dac47b7982034"
    url = "https://github.com/JuliaBinaryWrappers/llama_cpp_jll.jl/releases/download/llama_cpp-v0.0.9+0/llama_cpp.v0.0.9.x86_64-linux-gnu-cxx11.tar.gz"
[[llama_cpp]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "1966b1b2d9abb08a981d0b6005d4a45ee51261af"
libc = "musl"
os = "linux"

    [[llama_cpp.download]]
    sha256 = "6ab96b8f77aa7bcf6b6615def9210fcd9ca8b8f805436a409f335c9a2c223a29"
    url = "https://github.com/JuliaBinaryWrappers/llama_cpp_jll.jl/releases/download/llama_cpp-v0.0.9+0/llama_cpp.v0.0.9.x86_64-linux-musl-cxx03.tar.gz"
[[llama_cpp]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8668adc4e5dcfdfbd901b4e6688b1920fb53ba81"
libc = "musl"
os = "linux"

    [[llama_cpp.download]]
    sha256 = "61204664b823be2bbf145d2ddf574d8faf5589e4def493bf055311160ca7dd06"
    url = "https://github.com/JuliaBinaryWrappers/llama_cpp_jll.jl/releases/download/llama_cpp-v0.0.9+0/llama_cpp.v0.0.9.x86_64-linux-musl-cxx11.tar.gz"
[[llama_cpp]]
arch = "x86_64"
git-tree-sha1 = "e51166ab35dd6ef8277505026ab4266272e8aa84"
os = "freebsd"

    [[llama_cpp.download]]
    sha256 = "2a1426c62b0514a2505a14defaac917e9342d33c630fb6dfc4fac722f53090fd"
    url = "https://github.com/JuliaBinaryWrappers/llama_cpp_jll.jl/releases/download/llama_cpp-v0.0.9+0/llama_cpp.v0.0.9.x86_64-unknown-freebsd.tar.gz"
[[llama_cpp]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "32a3461072a4192cb607a5044dee9d180e5d4cc8"
os = "windows"

    [[llama_cpp.download]]
    sha256 = "527fe5762b8f4339f7364b25d1816542cd1b97a2296ccde9d1a5659ac8b07dad"
    url = "https://github.com/JuliaBinaryWrappers/llama_cpp_jll.jl/releases/download/llama_cpp-v0.0.9+0/llama_cpp.v0.0.9.x86_64-w64-mingw32-cxx03.tar.gz"
[[llama_cpp]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2c1db3ae05fd39d60b627b159b9d54327467029f"
os = "windows"

    [[llama_cpp.download]]
    sha256 = "89d7dffc246375b776b3ad39c0e276f415eb69b47327ae0f348960acd44f51d5"
    url = "https://github.com/JuliaBinaryWrappers/llama_cpp_jll.jl/releases/download/llama_cpp-v0.0.9+0/llama_cpp.v0.0.9.x86_64-w64-mingw32-cxx11.tar.gz"
