[[llama_cpp]]
arch = "aarch64"
git-tree-sha1 = "428e59831af5908aa8b749c21227a721a41465ed"
os = "macos"

    [[llama_cpp.download]]
    sha256 = "1720a31552f364ab5a0ec46e91a068b3c18da2ca01cc0a83a02627e8bf79efae"
    url = "https://github.com/JuliaBinaryWrappers/llama_cpp_jll.jl/releases/download/llama_cpp-v0.0.16+0/llama_cpp.v0.0.16.aarch64-apple-darwin.tar.gz"
[[llama_cpp]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "678b112af460b826090b38ead6287f3daf8469d0"
libc = "glibc"
os = "linux"

    [[llama_cpp.download]]
    sha256 = "30364b472ee2c9477a3e4c2c551a96cc044b7379167f07f0feb67ef0e76fbcae"
    url = "https://github.com/JuliaBinaryWrappers/llama_cpp_jll.jl/releases/download/llama_cpp-v0.0.16+0/llama_cpp.v0.0.16.aarch64-linux-gnu-cxx03.tar.gz"
[[llama_cpp]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "838d9e4dcf28556594c6ef9bdcacdd03ce200286"
libc = "glibc"
os = "linux"

    [[llama_cpp.download]]
    sha256 = "c5ea9b6f854f95c4b10c5bc8ab7db1163b337c3473383289084cd43e79995b32"
    url = "https://github.com/JuliaBinaryWrappers/llama_cpp_jll.jl/releases/download/llama_cpp-v0.0.16+0/llama_cpp.v0.0.16.aarch64-linux-gnu-cxx11.tar.gz"
[[llama_cpp]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "94b3b28f0db5e03b72b95d8aeeb367123a0b746c"
libc = "musl"
os = "linux"

    [[llama_cpp.download]]
    sha256 = "bfae487d585b7caa86633e8f5a041f2c61e9e2ac75ddcf44b6773e54cf09f190"
    url = "https://github.com/JuliaBinaryWrappers/llama_cpp_jll.jl/releases/download/llama_cpp-v0.0.16+0/llama_cpp.v0.0.16.aarch64-linux-musl-cxx03.tar.gz"
[[llama_cpp]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a7bd1942bb0ae3e45f574de1cd0fde5d4bb66412"
libc = "musl"
os = "linux"

    [[llama_cpp.download]]
    sha256 = "a0c5c04c564d97c6c86326deb7ba05258237a2d2374bbcb70c9934e7a09c03ed"
    url = "https://github.com/JuliaBinaryWrappers/llama_cpp_jll.jl/releases/download/llama_cpp-v0.0.16+0/llama_cpp.v0.0.16.aarch64-linux-musl-cxx11.tar.gz"
[[llama_cpp]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "42db73db07d7a529a339f12a052daecf488177df"
libc = "glibc"
os = "linux"

    [[llama_cpp.download]]
    sha256 = "26e423a8bd25dfe86c536c5de05b9864a3bf336f18240e5b3837255c89ec969d"
    url = "https://github.com/JuliaBinaryWrappers/llama_cpp_jll.jl/releases/download/llama_cpp-v0.0.16+0/llama_cpp.v0.0.16.i686-linux-gnu-cxx03.tar.gz"
[[llama_cpp]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "cfed83a802b84ad7fa5651aa38f9c20ca15a34cd"
libc = "glibc"
os = "linux"

    [[llama_cpp.download]]
    sha256 = "de43f5a17edd907d6aca449181ff30f09eeef78078c61c0a42081ccd9d881da1"
    url = "https://github.com/JuliaBinaryWrappers/llama_cpp_jll.jl/releases/download/llama_cpp-v0.0.16+0/llama_cpp.v0.0.16.i686-linux-gnu-cxx11.tar.gz"
[[llama_cpp]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "28a4cca7dc604ca8527d53490203561ca83d54d2"
libc = "musl"
os = "linux"

    [[llama_cpp.download]]
    sha256 = "8098c9e04dbad1bad0ccd9acd2a0d521786709d53eaad2f12f80487be4da0419"
    url = "https://github.com/JuliaBinaryWrappers/llama_cpp_jll.jl/releases/download/llama_cpp-v0.0.16+0/llama_cpp.v0.0.16.i686-linux-musl-cxx03.tar.gz"
[[llama_cpp]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "360d4b13e101344710e4bc8cf750e840449275a8"
libc = "musl"
os = "linux"

    [[llama_cpp.download]]
    sha256 = "940bafa3174685bf3a242767b1361ee1ee37ded93ec85132fc7157960e0f0677"
    url = "https://github.com/JuliaBinaryWrappers/llama_cpp_jll.jl/releases/download/llama_cpp-v0.0.16+0/llama_cpp.v0.0.16.i686-linux-musl-cxx11.tar.gz"
[[llama_cpp]]
arch = "x86_64"
git-tree-sha1 = "242026219352e7e14af6046ae578398f1bce0d19"
os = "macos"

    [[llama_cpp.download]]
    sha256 = "9c823633da495feed096dbf30879386de13c62eca135092a1ce41accddfca540"
    url = "https://github.com/JuliaBinaryWrappers/llama_cpp_jll.jl/releases/download/llama_cpp-v0.0.16+0/llama_cpp.v0.0.16.x86_64-apple-darwin.tar.gz"
[[llama_cpp]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "77db0cc5f50a63e66b5f938dd25afeda275d062a"
libc = "glibc"
os = "linux"

    [[llama_cpp.download]]
    sha256 = "9ddce688c50c76a16a590e6825cd66554a0a0d53ae3251606df21a0561db8190"
    url = "https://github.com/JuliaBinaryWrappers/llama_cpp_jll.jl/releases/download/llama_cpp-v0.0.16+0/llama_cpp.v0.0.16.x86_64-linux-gnu-cxx03.tar.gz"
[[llama_cpp]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "24e3f4fb7a2eb59ed58cb1b17135affbc2fcc10b"
libc = "glibc"
os = "linux"

    [[llama_cpp.download]]
    sha256 = "ebcf61d7a7ec287911dac5f0c36b4abeddad5af8a7fc71f8cbd57c3d2e3b72da"
    url = "https://github.com/JuliaBinaryWrappers/llama_cpp_jll.jl/releases/download/llama_cpp-v0.0.16+0/llama_cpp.v0.0.16.x86_64-linux-gnu-cxx11.tar.gz"
[[llama_cpp]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "56da83e1722b3b673cdd9be3713d7651545c88df"
libc = "musl"
os = "linux"

    [[llama_cpp.download]]
    sha256 = "2baad4140d727a33c68b79cd6758db002856e2b1725b06eddea90f274ea45655"
    url = "https://github.com/JuliaBinaryWrappers/llama_cpp_jll.jl/releases/download/llama_cpp-v0.0.16+0/llama_cpp.v0.0.16.x86_64-linux-musl-cxx03.tar.gz"
[[llama_cpp]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "46bfdc095a9652e60169e1374f2db01703cea515"
libc = "musl"
os = "linux"

    [[llama_cpp.download]]
    sha256 = "c733cc7d8af4a1490b3cbc7c213e4bdd9c3845de2cf254630c72e92513664cc3"
    url = "https://github.com/JuliaBinaryWrappers/llama_cpp_jll.jl/releases/download/llama_cpp-v0.0.16+0/llama_cpp.v0.0.16.x86_64-linux-musl-cxx11.tar.gz"
[[llama_cpp]]
arch = "x86_64"
git-tree-sha1 = "10e669b1cf8e429828a56790985a3e86959b2c54"
os = "freebsd"

    [[llama_cpp.download]]
    sha256 = "e4d1a3f56c755b1fdaf6cf62c2b5249752b66a6633249a190e1bbd9b21822ac9"
    url = "https://github.com/JuliaBinaryWrappers/llama_cpp_jll.jl/releases/download/llama_cpp-v0.0.16+0/llama_cpp.v0.0.16.x86_64-unknown-freebsd.tar.gz"
[[llama_cpp]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "782ef38bec2aff8c3e26d1fe739c6ef50e11ba19"
os = "windows"

    [[llama_cpp.download]]
    sha256 = "4a35eddda8688ff0aef4443d38fa23ab453b0bf74dd748ad83340a5623917253"
    url = "https://github.com/JuliaBinaryWrappers/llama_cpp_jll.jl/releases/download/llama_cpp-v0.0.16+0/llama_cpp.v0.0.16.x86_64-w64-mingw32-cxx03.tar.gz"
[[llama_cpp]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5113b66f1f9c4a98edab5188374b5b81359be8d6"
os = "windows"

    [[llama_cpp.download]]
    sha256 = "eb3979d21a064a3317cc07302863e597a1bad3067836a6eceeb33155d39e5f96"
    url = "https://github.com/JuliaBinaryWrappers/llama_cpp_jll.jl/releases/download/llama_cpp-v0.0.16+0/llama_cpp.v0.0.16.x86_64-w64-mingw32-cxx11.tar.gz"
