[[llama_cpp]]
arch = "aarch64"
git-tree-sha1 = "bc204f42cce57b2faaca6c42569b87a24d8dde07"
os = "macos"

    [[llama_cpp.download]]
    sha256 = "e77677e43afa2120609e0e115a813eb86ea1f489ee0dc29b949d912bd59e4340"
    url = "https://github.com/JuliaBinaryWrappers/llama_cpp_jll.jl/releases/download/llama_cpp-v0.0.14+0/llama_cpp.v0.0.14.aarch64-apple-darwin.tar.gz"
[[llama_cpp]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "1943f4bdc12ea8d183597cbf39501ec2e15373a6"
libc = "glibc"
os = "linux"

    [[llama_cpp.download]]
    sha256 = "77b5bda5e6069ae8ba495749e37f5926fb06fc4e832b677517d401a3a6662d1f"
    url = "https://github.com/JuliaBinaryWrappers/llama_cpp_jll.jl/releases/download/llama_cpp-v0.0.14+0/llama_cpp.v0.0.14.aarch64-linux-gnu-cxx03.tar.gz"
[[llama_cpp]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "248bf0d88be9e17c58b458503d4e7c29a6e8dca8"
libc = "glibc"
os = "linux"

    [[llama_cpp.download]]
    sha256 = "a11888283a1f1f2b3793f8a4c7ab6f4c7d7f7d0fb3d4a1a9d0c810480d7071ab"
    url = "https://github.com/JuliaBinaryWrappers/llama_cpp_jll.jl/releases/download/llama_cpp-v0.0.14+0/llama_cpp.v0.0.14.aarch64-linux-gnu-cxx11.tar.gz"
[[llama_cpp]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "aab862aa4389d5262303ead45c8683e9e272dbdd"
libc = "musl"
os = "linux"

    [[llama_cpp.download]]
    sha256 = "ddea854449e497226ec2e073802c2f114cfcf869c40fe5fb2cc08147bbc26310"
    url = "https://github.com/JuliaBinaryWrappers/llama_cpp_jll.jl/releases/download/llama_cpp-v0.0.14+0/llama_cpp.v0.0.14.aarch64-linux-musl-cxx03.tar.gz"
[[llama_cpp]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "46f84198f0a2c9d9386d58410465372cfbfccf19"
libc = "musl"
os = "linux"

    [[llama_cpp.download]]
    sha256 = "a7d4b6f201f764a0a4698e863ba2e5c6f95114d7846ba1fc709bdb8fc288d652"
    url = "https://github.com/JuliaBinaryWrappers/llama_cpp_jll.jl/releases/download/llama_cpp-v0.0.14+0/llama_cpp.v0.0.14.aarch64-linux-musl-cxx11.tar.gz"
[[llama_cpp]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a406beb4062a98af07666aa8530339bd4cf2bd19"
libc = "glibc"
os = "linux"

    [[llama_cpp.download]]
    sha256 = "9915e9dff35f4987608c411d4275c5c8269531536fce96102a29e9047a1629dd"
    url = "https://github.com/JuliaBinaryWrappers/llama_cpp_jll.jl/releases/download/llama_cpp-v0.0.14+0/llama_cpp.v0.0.14.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[llama_cpp]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1c3459dba190b6391606331603f38a519a0454b6"
libc = "glibc"
os = "linux"

    [[llama_cpp.download]]
    sha256 = "b79e835e72523056b677aaf06f02f3589c0d4043e1a214124c91e43f2a46f814"
    url = "https://github.com/JuliaBinaryWrappers/llama_cpp_jll.jl/releases/download/llama_cpp-v0.0.14+0/llama_cpp.v0.0.14.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[llama_cpp]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "837ae80834e1ca30b6786e3b7a6d6864c35788bb"
libc = "musl"
os = "linux"

    [[llama_cpp.download]]
    sha256 = "c1fab8b1c980201ecfea6110072af421e40d258372cefb46df529d0d46f1b87c"
    url = "https://github.com/JuliaBinaryWrappers/llama_cpp_jll.jl/releases/download/llama_cpp-v0.0.14+0/llama_cpp.v0.0.14.armv6l-linux-musleabihf-cxx03.tar.gz"
[[llama_cpp]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9e8fa97922d8718a3051c5cf47a3db49838ca608"
libc = "musl"
os = "linux"

    [[llama_cpp.download]]
    sha256 = "696d5b7c3bdda7f41fbd70d7c4ea117b243a5ca360aaf7cc9dcb665474906c4a"
    url = "https://github.com/JuliaBinaryWrappers/llama_cpp_jll.jl/releases/download/llama_cpp-v0.0.14+0/llama_cpp.v0.0.14.armv6l-linux-musleabihf-cxx11.tar.gz"
[[llama_cpp]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "4b579b118e2f023d20621d187421a1084cd87088"
libc = "glibc"
os = "linux"

    [[llama_cpp.download]]
    sha256 = "2b8aac80d0a70980f17e1a714242a332b0ec82e0e8a9550cda33296220923667"
    url = "https://github.com/JuliaBinaryWrappers/llama_cpp_jll.jl/releases/download/llama_cpp-v0.0.14+0/llama_cpp.v0.0.14.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[llama_cpp]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a6e655b3901c150ebc9a364c0faf3f6b43f8e147"
libc = "glibc"
os = "linux"

    [[llama_cpp.download]]
    sha256 = "2c8fabd6e16825383efa71a675263e093fcd3efaad40725dc8aa07d165029bc4"
    url = "https://github.com/JuliaBinaryWrappers/llama_cpp_jll.jl/releases/download/llama_cpp-v0.0.14+0/llama_cpp.v0.0.14.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[llama_cpp]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "87e3f0cdd880e7d43565ced95e12b4b7a834f484"
libc = "musl"
os = "linux"

    [[llama_cpp.download]]
    sha256 = "2ab93957eded616e0f4f95a0c39369754ff005a72942f3d37cee36cad0c0df91"
    url = "https://github.com/JuliaBinaryWrappers/llama_cpp_jll.jl/releases/download/llama_cpp-v0.0.14+0/llama_cpp.v0.0.14.armv7l-linux-musleabihf-cxx03.tar.gz"
[[llama_cpp]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "055e079a40be34777ee72b1f8306d15cce478e5e"
libc = "musl"
os = "linux"

    [[llama_cpp.download]]
    sha256 = "67ae9c9f4dfd0cc1fd1f0114569c744fd75559934764974a8c1a9c9083911483"
    url = "https://github.com/JuliaBinaryWrappers/llama_cpp_jll.jl/releases/download/llama_cpp-v0.0.14+0/llama_cpp.v0.0.14.armv7l-linux-musleabihf-cxx11.tar.gz"
[[llama_cpp]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "4f1f3d1f9e834bd4fd35259c0aad824cc07d1a13"
libc = "glibc"
os = "linux"

    [[llama_cpp.download]]
    sha256 = "bcdda9082f7db297b4e3015b87c8157ddf4b47883956bac85fd9ebe821abfa41"
    url = "https://github.com/JuliaBinaryWrappers/llama_cpp_jll.jl/releases/download/llama_cpp-v0.0.14+0/llama_cpp.v0.0.14.i686-linux-gnu-cxx03.tar.gz"
[[llama_cpp]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d6ba5b9e46257c14bc3fe422c973d771707a0a86"
libc = "glibc"
os = "linux"

    [[llama_cpp.download]]
    sha256 = "fdd0eb840ae56209b93684386b0e9676cb86a4dea4d929162616ebb157cb659a"
    url = "https://github.com/JuliaBinaryWrappers/llama_cpp_jll.jl/releases/download/llama_cpp-v0.0.14+0/llama_cpp.v0.0.14.i686-linux-gnu-cxx11.tar.gz"
[[llama_cpp]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "95410fb2919b0274dd74c2b11a8d350229e25295"
libc = "musl"
os = "linux"

    [[llama_cpp.download]]
    sha256 = "e42cbf6a4b778ef69e6ad6ee611d9b474aceaaa100b7db1d3ca6fcfff27be8aa"
    url = "https://github.com/JuliaBinaryWrappers/llama_cpp_jll.jl/releases/download/llama_cpp-v0.0.14+0/llama_cpp.v0.0.14.i686-linux-musl-cxx03.tar.gz"
[[llama_cpp]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7ea1c3c73038493a5347d479d46e194724a87415"
libc = "musl"
os = "linux"

    [[llama_cpp.download]]
    sha256 = "f11937671b9ee925c55e2f2885c91ff6ea3a18048b27a3408378f7deba92d451"
    url = "https://github.com/JuliaBinaryWrappers/llama_cpp_jll.jl/releases/download/llama_cpp-v0.0.14+0/llama_cpp.v0.0.14.i686-linux-musl-cxx11.tar.gz"
[[llama_cpp]]
arch = "x86_64"
git-tree-sha1 = "cdc6c79ed4ef94f79636eb93f4647eedd0548413"
os = "macos"

    [[llama_cpp.download]]
    sha256 = "a674342ec995e18277ab17ad149185dae2444f23aa1024380f030f6e3fe0369a"
    url = "https://github.com/JuliaBinaryWrappers/llama_cpp_jll.jl/releases/download/llama_cpp-v0.0.14+0/llama_cpp.v0.0.14.x86_64-apple-darwin.tar.gz"
[[llama_cpp]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "af4c77dfb6239f21ef97df056da07d26d118955c"
libc = "glibc"
os = "linux"

    [[llama_cpp.download]]
    sha256 = "6c1a64838e98fd4ea14cddd862003ae9aafc87ff1c37a7d84721dcd56a74f5b8"
    url = "https://github.com/JuliaBinaryWrappers/llama_cpp_jll.jl/releases/download/llama_cpp-v0.0.14+0/llama_cpp.v0.0.14.x86_64-linux-gnu-cxx03.tar.gz"
[[llama_cpp]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1f5cc5c2d7f3dc0e1f82b2d1892dd169facdb463"
libc = "glibc"
os = "linux"

    [[llama_cpp.download]]
    sha256 = "6590741a1e387fcf3378400db3aaab316ea3c548cb6ae8621386d75d151678ac"
    url = "https://github.com/JuliaBinaryWrappers/llama_cpp_jll.jl/releases/download/llama_cpp-v0.0.14+0/llama_cpp.v0.0.14.x86_64-linux-gnu-cxx11.tar.gz"
[[llama_cpp]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c22456a276222a19fb9d881603fa43de85110732"
libc = "musl"
os = "linux"

    [[llama_cpp.download]]
    sha256 = "e274e74e068f9e1d5c212f708fbe302a45658df29a92424667d04a064f0df026"
    url = "https://github.com/JuliaBinaryWrappers/llama_cpp_jll.jl/releases/download/llama_cpp-v0.0.14+0/llama_cpp.v0.0.14.x86_64-linux-musl-cxx03.tar.gz"
[[llama_cpp]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5f9c23c24f89b398531fa04e4daad02fa49cc415"
libc = "musl"
os = "linux"

    [[llama_cpp.download]]
    sha256 = "ead23e897d9feef9cb835efe01bfeb5d68ea19223b56fed95a1bed769254dc55"
    url = "https://github.com/JuliaBinaryWrappers/llama_cpp_jll.jl/releases/download/llama_cpp-v0.0.14+0/llama_cpp.v0.0.14.x86_64-linux-musl-cxx11.tar.gz"
[[llama_cpp]]
arch = "x86_64"
git-tree-sha1 = "7737fc718e8d2a5e87faaf3a8480ad505f8bd55a"
os = "freebsd"

    [[llama_cpp.download]]
    sha256 = "ad3feaebafe4827d887f7827f4e691743930809016e19ef3deb478dc752658dd"
    url = "https://github.com/JuliaBinaryWrappers/llama_cpp_jll.jl/releases/download/llama_cpp-v0.0.14+0/llama_cpp.v0.0.14.x86_64-unknown-freebsd.tar.gz"
[[llama_cpp]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "3b31107cba7818f1f9ab7e8384fdeeccc056d047"
os = "windows"

    [[llama_cpp.download]]
    sha256 = "5bb5e2f8af747aab6b5c088ff330c6422911c8c82ef1fda98e2de7392b00bf6c"
    url = "https://github.com/JuliaBinaryWrappers/llama_cpp_jll.jl/releases/download/llama_cpp-v0.0.14+0/llama_cpp.v0.0.14.x86_64-w64-mingw32-cxx03.tar.gz"
[[llama_cpp]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "fd16d884b29321a6949fe0f790ccc1f9643eb458"
os = "windows"

    [[llama_cpp.download]]
    sha256 = "ec25e4f76a305ac67e1fec76972b2580cf014163c775319e6a2525b81556fd6b"
    url = "https://github.com/JuliaBinaryWrappers/llama_cpp_jll.jl/releases/download/llama_cpp-v0.0.14+0/llama_cpp.v0.0.14.x86_64-w64-mingw32-cxx11.tar.gz"
