[[llama_cpp]]
arch = "aarch64"
git-tree-sha1 = "8f042eb6d7be7f02b59a71d30ad4d81b052cfaa1"
os = "macos"

    [[llama_cpp.download]]
    sha256 = "d3b02081a3e0dfd97172dc8450298e4ef18f589625edce4d6101dde456b79dd1"
    url = "https://github.com/JuliaBinaryWrappers/llama_cpp_jll.jl/releases/download/llama_cpp-v0.0.10+0/llama_cpp.v0.0.10.aarch64-apple-darwin.tar.gz"
[[llama_cpp]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "066b7b65df7927c402734f4c6cc685be2fb5d763"
libc = "glibc"
os = "linux"

    [[llama_cpp.download]]
    sha256 = "1f4f46971c02e9961619038766965c2c9b6e3a5c8f1bf27b30d4f881716ea7b2"
    url = "https://github.com/JuliaBinaryWrappers/llama_cpp_jll.jl/releases/download/llama_cpp-v0.0.10+0/llama_cpp.v0.0.10.aarch64-linux-gnu-cxx03.tar.gz"
[[llama_cpp]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e21a3e94f0c8116db63438aeab657340b4884813"
libc = "glibc"
os = "linux"

    [[llama_cpp.download]]
    sha256 = "d541b7bae0f7e63579a8bb86da02c7bf7eebaa1da31b559b27ea7167df82c8c5"
    url = "https://github.com/JuliaBinaryWrappers/llama_cpp_jll.jl/releases/download/llama_cpp-v0.0.10+0/llama_cpp.v0.0.10.aarch64-linux-gnu-cxx11.tar.gz"
[[llama_cpp]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "82f5419978467a166fe8ddcaf2cc06edd16e0015"
libc = "musl"
os = "linux"

    [[llama_cpp.download]]
    sha256 = "e9a5ace9ca66952fe40ff5a8375184a532ae5d9a0b376f6826cd08f26fc67e9a"
    url = "https://github.com/JuliaBinaryWrappers/llama_cpp_jll.jl/releases/download/llama_cpp-v0.0.10+0/llama_cpp.v0.0.10.aarch64-linux-musl-cxx03.tar.gz"
[[llama_cpp]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f33e1cf18c9446d515bea2514a1976fef84f51c7"
libc = "musl"
os = "linux"

    [[llama_cpp.download]]
    sha256 = "d2d42e9e5e69e43eaba130968714360910ee0455e1bf75d8b9577c981906871e"
    url = "https://github.com/JuliaBinaryWrappers/llama_cpp_jll.jl/releases/download/llama_cpp-v0.0.10+0/llama_cpp.v0.0.10.aarch64-linux-musl-cxx11.tar.gz"
[[llama_cpp]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c468bdb14a1ba225af7ed52202eac38f15318fa0"
libc = "glibc"
os = "linux"

    [[llama_cpp.download]]
    sha256 = "27643a456cc154fb0c2038bb561b06d99f380d1c38a536304bd0a8a2e2d3f002"
    url = "https://github.com/JuliaBinaryWrappers/llama_cpp_jll.jl/releases/download/llama_cpp-v0.0.10+0/llama_cpp.v0.0.10.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[llama_cpp]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1c27720725a34982d944d85d190f82521d80b2a3"
libc = "glibc"
os = "linux"

    [[llama_cpp.download]]
    sha256 = "54209f05079244a46c4413cc53cc347671ade5ae15087b5783d3327fd0f91dd8"
    url = "https://github.com/JuliaBinaryWrappers/llama_cpp_jll.jl/releases/download/llama_cpp-v0.0.10+0/llama_cpp.v0.0.10.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[llama_cpp]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ca7c87d08cd37c500b07473ecbf1e80fe7d125c8"
libc = "musl"
os = "linux"

    [[llama_cpp.download]]
    sha256 = "2ad34fcb9720b97e22a09cf5a15d130931ff6056eb7dd5c611580dd6bca57e62"
    url = "https://github.com/JuliaBinaryWrappers/llama_cpp_jll.jl/releases/download/llama_cpp-v0.0.10+0/llama_cpp.v0.0.10.armv6l-linux-musleabihf-cxx03.tar.gz"
[[llama_cpp]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c40e433503bd04ac741b45ee3408a61c62adf531"
libc = "musl"
os = "linux"

    [[llama_cpp.download]]
    sha256 = "b1836cf27b4a6aa3d79b04e1bf4c96ed0c70c7690cbc5adeaf95935c46c43b73"
    url = "https://github.com/JuliaBinaryWrappers/llama_cpp_jll.jl/releases/download/llama_cpp-v0.0.10+0/llama_cpp.v0.0.10.armv6l-linux-musleabihf-cxx11.tar.gz"
[[llama_cpp]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "05e0923f01959f9931ad23c17730f3a17e84eafc"
libc = "glibc"
os = "linux"

    [[llama_cpp.download]]
    sha256 = "ac31afad8861b76dfcfb4a1361eb09f75c91e747e5cf4d65f8d863be5e242b5f"
    url = "https://github.com/JuliaBinaryWrappers/llama_cpp_jll.jl/releases/download/llama_cpp-v0.0.10+0/llama_cpp.v0.0.10.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[llama_cpp]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8415a0a07c401e6618c7b9db3e6fbf8aec161c6e"
libc = "glibc"
os = "linux"

    [[llama_cpp.download]]
    sha256 = "865e9038d185f6ba3817afec55093e86152b70806661d3b391c5ff2c7e948996"
    url = "https://github.com/JuliaBinaryWrappers/llama_cpp_jll.jl/releases/download/llama_cpp-v0.0.10+0/llama_cpp.v0.0.10.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[llama_cpp]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "aa5af03661a480dfc91ae5009ba0087cd9675620"
libc = "musl"
os = "linux"

    [[llama_cpp.download]]
    sha256 = "514978c2528440c17079c6f5ed5a6b03d9a4e7c7ca4b8910176d049042ac899f"
    url = "https://github.com/JuliaBinaryWrappers/llama_cpp_jll.jl/releases/download/llama_cpp-v0.0.10+0/llama_cpp.v0.0.10.armv7l-linux-musleabihf-cxx03.tar.gz"
[[llama_cpp]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2c1b56c176f0c55245942028e33b6743504f95a7"
libc = "musl"
os = "linux"

    [[llama_cpp.download]]
    sha256 = "516e48fa4edf84eafc6fd7e032e3e3f4130e613d47f18294a8e46b9bf0c04981"
    url = "https://github.com/JuliaBinaryWrappers/llama_cpp_jll.jl/releases/download/llama_cpp-v0.0.10+0/llama_cpp.v0.0.10.armv7l-linux-musleabihf-cxx11.tar.gz"
[[llama_cpp]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "5547aa65abcd45094499cbae201a0e21dc0c757c"
libc = "glibc"
os = "linux"

    [[llama_cpp.download]]
    sha256 = "0607eebb78ed4b167fb3b773973d4665ffaf3eda3a9444dda53595b280550d4c"
    url = "https://github.com/JuliaBinaryWrappers/llama_cpp_jll.jl/releases/download/llama_cpp-v0.0.10+0/llama_cpp.v0.0.10.i686-linux-gnu-cxx03.tar.gz"
[[llama_cpp]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "71585a0e61daebdab0f03ab25280e4852a36d62e"
libc = "glibc"
os = "linux"

    [[llama_cpp.download]]
    sha256 = "9dab310aea23fb2cfa76ef91e69d33f1380516ac6039766580d9da760fae547b"
    url = "https://github.com/JuliaBinaryWrappers/llama_cpp_jll.jl/releases/download/llama_cpp-v0.0.10+0/llama_cpp.v0.0.10.i686-linux-gnu-cxx11.tar.gz"
[[llama_cpp]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c9eda9e366de641e86a48b616330e94b3d8f668f"
libc = "musl"
os = "linux"

    [[llama_cpp.download]]
    sha256 = "aa9f7d6d71a45653ae903de7001d8c4a37df7cac35ed85d2679dde9b9c0889c3"
    url = "https://github.com/JuliaBinaryWrappers/llama_cpp_jll.jl/releases/download/llama_cpp-v0.0.10+0/llama_cpp.v0.0.10.i686-linux-musl-cxx03.tar.gz"
[[llama_cpp]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "504a442d5941133648d88d7279208126df0b6f9a"
libc = "musl"
os = "linux"

    [[llama_cpp.download]]
    sha256 = "74cfde7b9db21301a296e5fe646f2267aedf7a02f4e7dd0dc28be8c6a73ac76d"
    url = "https://github.com/JuliaBinaryWrappers/llama_cpp_jll.jl/releases/download/llama_cpp-v0.0.10+0/llama_cpp.v0.0.10.i686-linux-musl-cxx11.tar.gz"
[[llama_cpp]]
arch = "x86_64"
git-tree-sha1 = "6f3d3ee4b01f789a34f1c93275a6624750b363e4"
os = "macos"

    [[llama_cpp.download]]
    sha256 = "5ec8aaa6890e0a8ac594c6916da9218d10ea4a39cc253fedd31eb87e7f497cc1"
    url = "https://github.com/JuliaBinaryWrappers/llama_cpp_jll.jl/releases/download/llama_cpp-v0.0.10+0/llama_cpp.v0.0.10.x86_64-apple-darwin.tar.gz"
[[llama_cpp]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "729bf15572b6963b1d1d36c5069d75f20915d7a1"
libc = "glibc"
os = "linux"

    [[llama_cpp.download]]
    sha256 = "6ac8af5d42db9d226d1c9385afd211c0ec5bced07369d04f0acc971a1dac025b"
    url = "https://github.com/JuliaBinaryWrappers/llama_cpp_jll.jl/releases/download/llama_cpp-v0.0.10+0/llama_cpp.v0.0.10.x86_64-linux-gnu-cxx03.tar.gz"
[[llama_cpp]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "31d8a93fa6b37284f73b245a4a2e285bfd02aee2"
libc = "glibc"
os = "linux"

    [[llama_cpp.download]]
    sha256 = "13f90d5739704642ef03073c59328efdcc309f9a1b235d63ea46b0483beaefc4"
    url = "https://github.com/JuliaBinaryWrappers/llama_cpp_jll.jl/releases/download/llama_cpp-v0.0.10+0/llama_cpp.v0.0.10.x86_64-linux-gnu-cxx11.tar.gz"
[[llama_cpp]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "55a1b5a0ab06a81a518ffb6e8b1f3bb7a5538fca"
libc = "musl"
os = "linux"

    [[llama_cpp.download]]
    sha256 = "32317e1b9c32204325bca82646fd32547299c870f2aac2346f6c6a93ac00be83"
    url = "https://github.com/JuliaBinaryWrappers/llama_cpp_jll.jl/releases/download/llama_cpp-v0.0.10+0/llama_cpp.v0.0.10.x86_64-linux-musl-cxx03.tar.gz"
[[llama_cpp]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4c54980254cb2362b49206bbf136288346a13fdc"
libc = "musl"
os = "linux"

    [[llama_cpp.download]]
    sha256 = "fb757a25e5bd5513ea7577801dae20c1ec67a237448b3b036b5c7f098dcf46d4"
    url = "https://github.com/JuliaBinaryWrappers/llama_cpp_jll.jl/releases/download/llama_cpp-v0.0.10+0/llama_cpp.v0.0.10.x86_64-linux-musl-cxx11.tar.gz"
[[llama_cpp]]
arch = "x86_64"
git-tree-sha1 = "5c373fd98e7ac1ecc26f4348af070e6b8db1615b"
os = "freebsd"

    [[llama_cpp.download]]
    sha256 = "a5deb14fc3ee9707376a3053e479ad420e1f040c4789ea3ea53a0b7275b188da"
    url = "https://github.com/JuliaBinaryWrappers/llama_cpp_jll.jl/releases/download/llama_cpp-v0.0.10+0/llama_cpp.v0.0.10.x86_64-unknown-freebsd.tar.gz"
[[llama_cpp]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ebbf8201f943a6c26c87ce8bc9538e481f027cde"
os = "windows"

    [[llama_cpp.download]]
    sha256 = "a47ca952dee989ec4e41843bca41460b47a4cc925287bbd75af79e4aa967a167"
    url = "https://github.com/JuliaBinaryWrappers/llama_cpp_jll.jl/releases/download/llama_cpp-v0.0.10+0/llama_cpp.v0.0.10.x86_64-w64-mingw32-cxx03.tar.gz"
[[llama_cpp]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5b6f76f25b9fd2b132ee78601fdc9eb01401b4bf"
os = "windows"

    [[llama_cpp.download]]
    sha256 = "e163d3d13cad7fc13b518e04f057cece90c86efb7160a663a3ba583726af9928"
    url = "https://github.com/JuliaBinaryWrappers/llama_cpp_jll.jl/releases/download/llama_cpp-v0.0.10+0/llama_cpp.v0.0.10.x86_64-w64-mingw32-cxx11.tar.gz"
