[[llama_cpp]]
arch = "aarch64"
git-tree-sha1 = "a4723c465b8d1365137081942b2e3880d3d5dc5b"
os = "macos"

    [[llama_cpp.download]]
    sha256 = "d3185a2c51bf9fbf0378f61adce4d692aeeb88927b09eea370db0ebd99b2cc31"
    url = "https://github.com/JuliaBinaryWrappers/llama_cpp_jll.jl/releases/download/llama_cpp-v0.0.6+1/llama_cpp.v0.0.6.aarch64-apple-darwin.tar.gz"
[[llama_cpp]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "23a5c5489b7dca81ff4bf7abc1cd9b5c757d213b"
libc = "glibc"
os = "linux"

    [[llama_cpp.download]]
    sha256 = "77afdac69baa93586852396a0d699906ee4750a23c16ea73f360a2e6e27aaf83"
    url = "https://github.com/JuliaBinaryWrappers/llama_cpp_jll.jl/releases/download/llama_cpp-v0.0.6+1/llama_cpp.v0.0.6.aarch64-linux-gnu-cxx03.tar.gz"
[[llama_cpp]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b7a5579d5bbf0feed2108c488e5dbc1484cb2b60"
libc = "glibc"
os = "linux"

    [[llama_cpp.download]]
    sha256 = "c7c028181800c316c7061ebd6eeaf9feb2079ad91cd8686a50e39cf5590d8c1e"
    url = "https://github.com/JuliaBinaryWrappers/llama_cpp_jll.jl/releases/download/llama_cpp-v0.0.6+1/llama_cpp.v0.0.6.aarch64-linux-gnu-cxx11.tar.gz"
[[llama_cpp]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "1ec4872cfbc7a9a71ea02050581d201c63fb5338"
libc = "musl"
os = "linux"

    [[llama_cpp.download]]
    sha256 = "0bebb4a3d0efe0850094ed158c5859643ab62388cc69dadbab40015d336b6f36"
    url = "https://github.com/JuliaBinaryWrappers/llama_cpp_jll.jl/releases/download/llama_cpp-v0.0.6+1/llama_cpp.v0.0.6.aarch64-linux-musl-cxx03.tar.gz"
[[llama_cpp]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "75356ba40ade12f68b8a28dbbe4eeb5012ad7840"
libc = "musl"
os = "linux"

    [[llama_cpp.download]]
    sha256 = "a118a9b48525d0e40efbbf672ed5c1b6afdabf8aae39c9af7fa5f21ec595f428"
    url = "https://github.com/JuliaBinaryWrappers/llama_cpp_jll.jl/releases/download/llama_cpp-v0.0.6+1/llama_cpp.v0.0.6.aarch64-linux-musl-cxx11.tar.gz"
[[llama_cpp]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "87846b70ec51fd9c4352643c67117e750d1d173c"
libc = "glibc"
os = "linux"

    [[llama_cpp.download]]
    sha256 = "675ff6e6212e6edea4319fd2f64dea697e872243a8756eba9d4546a10aecf5a1"
    url = "https://github.com/JuliaBinaryWrappers/llama_cpp_jll.jl/releases/download/llama_cpp-v0.0.6+1/llama_cpp.v0.0.6.i686-linux-gnu-cxx03.tar.gz"
[[llama_cpp]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "32358701debd8ce86141a29ff172d6afa64dc1e4"
libc = "glibc"
os = "linux"

    [[llama_cpp.download]]
    sha256 = "2708c1da71ba5307ef1cab5e95815338847616c9c6f81d2bbeae66efc809159e"
    url = "https://github.com/JuliaBinaryWrappers/llama_cpp_jll.jl/releases/download/llama_cpp-v0.0.6+1/llama_cpp.v0.0.6.i686-linux-gnu-cxx11.tar.gz"
[[llama_cpp]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "5512064494eaa90c4e3d881dd35bfee910313e71"
libc = "musl"
os = "linux"

    [[llama_cpp.download]]
    sha256 = "100e932d88b9f4f90fa6583aaa65e9623d596d9440a1172073d704f24d634bc9"
    url = "https://github.com/JuliaBinaryWrappers/llama_cpp_jll.jl/releases/download/llama_cpp-v0.0.6+1/llama_cpp.v0.0.6.i686-linux-musl-cxx03.tar.gz"
[[llama_cpp]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "09e1b4dff9320c29d8fc424ed729a5976b701686"
libc = "musl"
os = "linux"

    [[llama_cpp.download]]
    sha256 = "9eb223e3a0d4ea8ec68a735ce03f6b5d5b5082eaa967b6f182c3c86a20195afb"
    url = "https://github.com/JuliaBinaryWrappers/llama_cpp_jll.jl/releases/download/llama_cpp-v0.0.6+1/llama_cpp.v0.0.6.i686-linux-musl-cxx11.tar.gz"
[[llama_cpp]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "1df727ad8fc368bc1adb3839b85a68e203db878a"
os = "windows"

    [[llama_cpp.download]]
    sha256 = "13470165cbe14bfd3a82a78083ad054e0d8ca1b0ce9909cfd12ad7b52bea729f"
    url = "https://github.com/JuliaBinaryWrappers/llama_cpp_jll.jl/releases/download/llama_cpp-v0.0.6+1/llama_cpp.v0.0.6.i686-w64-mingw32-cxx03.tar.gz"
[[llama_cpp]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a6b0899e247a79d169040644473760d54abd0b96"
os = "windows"

    [[llama_cpp.download]]
    sha256 = "bbd51285eb1580c988ad854af454a981c75ccfde8f195d0d86de24522d39a249"
    url = "https://github.com/JuliaBinaryWrappers/llama_cpp_jll.jl/releases/download/llama_cpp-v0.0.6+1/llama_cpp.v0.0.6.i686-w64-mingw32-cxx11.tar.gz"
[[llama_cpp]]
arch = "x86_64"
git-tree-sha1 = "032c39aa1a5530b7d006fc06b5444faf83007ee4"
os = "macos"

    [[llama_cpp.download]]
    sha256 = "e4e429737cce5d675c60ff7bbf14ef21c9cc693818704d31b82a6611a4d57657"
    url = "https://github.com/JuliaBinaryWrappers/llama_cpp_jll.jl/releases/download/llama_cpp-v0.0.6+1/llama_cpp.v0.0.6.x86_64-apple-darwin.tar.gz"
[[llama_cpp]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "3d0ab4a673b7c99388114dd9d3b892bba9ecc9d9"
libc = "glibc"
os = "linux"

    [[llama_cpp.download]]
    sha256 = "436fc88db31cace7580ea6c197c705b297ff1b4cdae113fc08b76b8bed794a36"
    url = "https://github.com/JuliaBinaryWrappers/llama_cpp_jll.jl/releases/download/llama_cpp-v0.0.6+1/llama_cpp.v0.0.6.x86_64-linux-gnu-cxx03.tar.gz"
[[llama_cpp]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7b1f4a2b38f561e6885a7da37777dc5b89f16298"
libc = "glibc"
os = "linux"

    [[llama_cpp.download]]
    sha256 = "f7ddecb2c8921772a9e2c2cf4875f2b1ba58b6f5b2e69093ade2b9c5f3644b1a"
    url = "https://github.com/JuliaBinaryWrappers/llama_cpp_jll.jl/releases/download/llama_cpp-v0.0.6+1/llama_cpp.v0.0.6.x86_64-linux-gnu-cxx11.tar.gz"
[[llama_cpp]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "26732a1768bd86315a231b1e778c10340f39f243"
libc = "musl"
os = "linux"

    [[llama_cpp.download]]
    sha256 = "c3f1c82def151c7cdf9ff5d58fed4813fbf7346d09c18578ffd329731ae70ec3"
    url = "https://github.com/JuliaBinaryWrappers/llama_cpp_jll.jl/releases/download/llama_cpp-v0.0.6+1/llama_cpp.v0.0.6.x86_64-linux-musl-cxx03.tar.gz"
[[llama_cpp]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5603de9c304a0d140baf7cf2418906ae80b957c1"
libc = "musl"
os = "linux"

    [[llama_cpp.download]]
    sha256 = "f3e46d1e45f53b6bd644909db7edb4ba70fe2b3e88798c63f75e4bcd9eac021a"
    url = "https://github.com/JuliaBinaryWrappers/llama_cpp_jll.jl/releases/download/llama_cpp-v0.0.6+1/llama_cpp.v0.0.6.x86_64-linux-musl-cxx11.tar.gz"
[[llama_cpp]]
arch = "x86_64"
git-tree-sha1 = "e257d72dfe32264f893ff8111b0e4b207b16877f"
os = "freebsd"

    [[llama_cpp.download]]
    sha256 = "ffb218349c8a7a98766bbba906a76dfa6e39338dba60885fb224629adb1738ed"
    url = "https://github.com/JuliaBinaryWrappers/llama_cpp_jll.jl/releases/download/llama_cpp-v0.0.6+1/llama_cpp.v0.0.6.x86_64-unknown-freebsd.tar.gz"
[[llama_cpp]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "7888c93583fab44c76ec6519712b2954d1cc6fbb"
os = "windows"

    [[llama_cpp.download]]
    sha256 = "4388754dccef2dd66bdb62e36897e21ff018a3451b6700a84e271088b4c01b90"
    url = "https://github.com/JuliaBinaryWrappers/llama_cpp_jll.jl/releases/download/llama_cpp-v0.0.6+1/llama_cpp.v0.0.6.x86_64-w64-mingw32-cxx03.tar.gz"
[[llama_cpp]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d8603de95003c85598c2c338191f640c223ebaf6"
os = "windows"

    [[llama_cpp.download]]
    sha256 = "da2f2d90a45b19048ec6ae8900a1428900568a0eb46212285cdfa8195219f241"
    url = "https://github.com/JuliaBinaryWrappers/llama_cpp_jll.jl/releases/download/llama_cpp-v0.0.6+1/llama_cpp.v0.0.6.x86_64-w64-mingw32-cxx11.tar.gz"
