[[llama_cpp]]
arch = "aarch64"
git-tree-sha1 = "03104a26910f631a011c4d4b1b9f4d29a564420e"
os = "macos"

    [[llama_cpp.download]]
    sha256 = "bb690fb06bb17e8b8b1309a0024feabaa4ed89f6230d0e4e3e9b124b013ed49a"
    url = "https://github.com/JuliaBinaryWrappers/llama_cpp_jll.jl/releases/download/llama_cpp-v0.0.4+0/llama_cpp.v0.0.4.aarch64-apple-darwin.tar.gz"
[[llama_cpp]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "bd935b8bdf8c93d424f465ad2aa0cf61f99a67d2"
libc = "glibc"
os = "linux"

    [[llama_cpp.download]]
    sha256 = "e00f4e52995e13962678f17c266ec021f3891302e9fde9afecc139b6482cb52a"
    url = "https://github.com/JuliaBinaryWrappers/llama_cpp_jll.jl/releases/download/llama_cpp-v0.0.4+0/llama_cpp.v0.0.4.aarch64-linux-gnu-cxx03.tar.gz"
[[llama_cpp]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1272a3280d53304ec103f40f0de45f91fe6f9b9f"
libc = "glibc"
os = "linux"

    [[llama_cpp.download]]
    sha256 = "6ba450de0d1f330cbfeaa5f3996a02864ba5e485d5af8ec40e0686525550238d"
    url = "https://github.com/JuliaBinaryWrappers/llama_cpp_jll.jl/releases/download/llama_cpp-v0.0.4+0/llama_cpp.v0.0.4.aarch64-linux-gnu-cxx11.tar.gz"
[[llama_cpp]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "4f471a9c0bc3fe27018d771f70f437be9ba2c497"
libc = "musl"
os = "linux"

    [[llama_cpp.download]]
    sha256 = "0007a1079266e299b16167b49ebded32224fd04a744e9b706cde73866177fbd9"
    url = "https://github.com/JuliaBinaryWrappers/llama_cpp_jll.jl/releases/download/llama_cpp-v0.0.4+0/llama_cpp.v0.0.4.aarch64-linux-musl-cxx03.tar.gz"
[[llama_cpp]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "80bde4d54d48515cdd478c0957be86d83e9d7457"
libc = "musl"
os = "linux"

    [[llama_cpp.download]]
    sha256 = "b3ac2ebe0d5795ce48d6b3717e50611b359ac602372ddd09abd6a0aff4680cd7"
    url = "https://github.com/JuliaBinaryWrappers/llama_cpp_jll.jl/releases/download/llama_cpp-v0.0.4+0/llama_cpp.v0.0.4.aarch64-linux-musl-cxx11.tar.gz"
[[llama_cpp]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "50e734693b73b3ea3fb3b472a95ca4418fd6e8fb"
libc = "glibc"
os = "linux"

    [[llama_cpp.download]]
    sha256 = "d151dff0cb8943e3ef12004d80a34e814fec23d87d5e91249894d07bcbd0c1a7"
    url = "https://github.com/JuliaBinaryWrappers/llama_cpp_jll.jl/releases/download/llama_cpp-v0.0.4+0/llama_cpp.v0.0.4.i686-linux-gnu-cxx03.tar.gz"
[[llama_cpp]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "25b728442b05effaabef97bc278e55d12983bbc5"
libc = "glibc"
os = "linux"

    [[llama_cpp.download]]
    sha256 = "44d75e51d5ecadbee2562cc06703a94163dfa5526ec5dfb05dc092ed5aa82fee"
    url = "https://github.com/JuliaBinaryWrappers/llama_cpp_jll.jl/releases/download/llama_cpp-v0.0.4+0/llama_cpp.v0.0.4.i686-linux-gnu-cxx11.tar.gz"
[[llama_cpp]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "1a58a9e38d2af8f18838ef2588f0f78aec935f2b"
libc = "musl"
os = "linux"

    [[llama_cpp.download]]
    sha256 = "8e2cc7c6e17a7b51a699452795694eea68aca6b6aaa1eec35206c8a0c5b36efd"
    url = "https://github.com/JuliaBinaryWrappers/llama_cpp_jll.jl/releases/download/llama_cpp-v0.0.4+0/llama_cpp.v0.0.4.i686-linux-musl-cxx03.tar.gz"
[[llama_cpp]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e1d8e37c944259f73571007283f32d9d7b671065"
libc = "musl"
os = "linux"

    [[llama_cpp.download]]
    sha256 = "10187a729d4ab795f79852df3320b5c99423b2c79bc15c7b34ca4f94cf3a7e62"
    url = "https://github.com/JuliaBinaryWrappers/llama_cpp_jll.jl/releases/download/llama_cpp-v0.0.4+0/llama_cpp.v0.0.4.i686-linux-musl-cxx11.tar.gz"
[[llama_cpp]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e80ee4b398669f017ca3553dcc9cac40815bd0f1"
os = "windows"

    [[llama_cpp.download]]
    sha256 = "448c28c63fbe81364489f6bb365f5fe2d6c7a94a93288949db08f7d274e2c7a2"
    url = "https://github.com/JuliaBinaryWrappers/llama_cpp_jll.jl/releases/download/llama_cpp-v0.0.4+0/llama_cpp.v0.0.4.i686-w64-mingw32-cxx03.tar.gz"
[[llama_cpp]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "dd04231c1744791fe936763bfb0ea418eb5b1c5b"
os = "windows"

    [[llama_cpp.download]]
    sha256 = "1cc440083b007600c31d80676a07cebf9dcc85c059421e6fd2b8e6070720bcdb"
    url = "https://github.com/JuliaBinaryWrappers/llama_cpp_jll.jl/releases/download/llama_cpp-v0.0.4+0/llama_cpp.v0.0.4.i686-w64-mingw32-cxx11.tar.gz"
[[llama_cpp]]
arch = "x86_64"
git-tree-sha1 = "b71490ef722ca12dc7189f7f8bf5638a3cb0d6a2"
os = "macos"

    [[llama_cpp.download]]
    sha256 = "a74214038ee7c42de0154168d21801fd8d8ef9f588bb7c0b818e87c282c39ddd"
    url = "https://github.com/JuliaBinaryWrappers/llama_cpp_jll.jl/releases/download/llama_cpp-v0.0.4+0/llama_cpp.v0.0.4.x86_64-apple-darwin.tar.gz"
[[llama_cpp]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d519f7eec3b1a644089e931b7970b5f324174e75"
libc = "glibc"
os = "linux"

    [[llama_cpp.download]]
    sha256 = "e66937b719d3425276dedd65193fd5aae4264ebe52286dee896c3c46e2422a57"
    url = "https://github.com/JuliaBinaryWrappers/llama_cpp_jll.jl/releases/download/llama_cpp-v0.0.4+0/llama_cpp.v0.0.4.x86_64-linux-gnu-cxx03.tar.gz"
[[llama_cpp]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b27dd5a86bbb0732e52fab2747291ba6c50727ef"
libc = "glibc"
os = "linux"

    [[llama_cpp.download]]
    sha256 = "bf852b7c8b04cdd332e5585fb7e8cfb8dfc3f9cdce819207a434e30c2735bef2"
    url = "https://github.com/JuliaBinaryWrappers/llama_cpp_jll.jl/releases/download/llama_cpp-v0.0.4+0/llama_cpp.v0.0.4.x86_64-linux-gnu-cxx11.tar.gz"
[[llama_cpp]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "56f70c5b51251d9e3820bbaffd3399190719ae04"
libc = "musl"
os = "linux"

    [[llama_cpp.download]]
    sha256 = "daba8aa296580d287c17154b0450f5e7fb57938ed591b47ab0c533f9c6b89ad5"
    url = "https://github.com/JuliaBinaryWrappers/llama_cpp_jll.jl/releases/download/llama_cpp-v0.0.4+0/llama_cpp.v0.0.4.x86_64-linux-musl-cxx03.tar.gz"
[[llama_cpp]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "419f34ee46afea72b0677249d429b7c90394ed63"
libc = "musl"
os = "linux"

    [[llama_cpp.download]]
    sha256 = "62b45a66d3a25c284e0441a15a45228dc14a19b1853e81aaeaa1e78b2fb54672"
    url = "https://github.com/JuliaBinaryWrappers/llama_cpp_jll.jl/releases/download/llama_cpp-v0.0.4+0/llama_cpp.v0.0.4.x86_64-linux-musl-cxx11.tar.gz"
[[llama_cpp]]
arch = "x86_64"
git-tree-sha1 = "817cdd012c63de468af36e415f3c51a1cb8a6ccc"
os = "freebsd"

    [[llama_cpp.download]]
    sha256 = "b46188d6d01eb1c666b87745247ad3e8fe7b0390e360202745ca6491f8ea4480"
    url = "https://github.com/JuliaBinaryWrappers/llama_cpp_jll.jl/releases/download/llama_cpp-v0.0.4+0/llama_cpp.v0.0.4.x86_64-unknown-freebsd.tar.gz"
[[llama_cpp]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "b1d514639bc62e19b74cda034c2b4b7b3e69e244"
os = "windows"

    [[llama_cpp.download]]
    sha256 = "930a4c330531124724970c68d4b669f659f721d07b35965e6175b1947a970c85"
    url = "https://github.com/JuliaBinaryWrappers/llama_cpp_jll.jl/releases/download/llama_cpp-v0.0.4+0/llama_cpp.v0.0.4.x86_64-w64-mingw32-cxx03.tar.gz"
[[llama_cpp]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "861e25f8f9d13b6856efa864b1abd3121764978b"
os = "windows"

    [[llama_cpp.download]]
    sha256 = "f5712a25482fcf72a43956034dde0da20133d34893a9a58ea172995e68963075"
    url = "https://github.com/JuliaBinaryWrappers/llama_cpp_jll.jl/releases/download/llama_cpp-v0.0.4+0/llama_cpp.v0.0.4.x86_64-w64-mingw32-cxx11.tar.gz"
