[[llama_cpp]]
arch = "aarch64"
git-tree-sha1 = "250cce1e5568a46085cfa1a86174c0539d70be65"
os = "macos"

    [[llama_cpp.download]]
    sha256 = "c45122c38d0dc5d194e06bbaaf3c762fddb5ef5c3918001a8a755a99c863e68f"
    url = "https://github.com/JuliaBinaryWrappers/llama_cpp_jll.jl/releases/download/llama_cpp-v0.0.5+0/llama_cpp.v0.0.5.aarch64-apple-darwin.tar.gz"
[[llama_cpp]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "5bbae2e5d112c86bdbb73705618e7db01cae3516"
libc = "glibc"
os = "linux"

    [[llama_cpp.download]]
    sha256 = "4a1750d1be802b3ade4d7470c21f3f0c67beb2b4be866655f799e2e8666c6e5c"
    url = "https://github.com/JuliaBinaryWrappers/llama_cpp_jll.jl/releases/download/llama_cpp-v0.0.5+0/llama_cpp.v0.0.5.aarch64-linux-gnu-cxx03.tar.gz"
[[llama_cpp]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "24504b7b47daf6412f975bf715208f31ad9c31fe"
libc = "glibc"
os = "linux"

    [[llama_cpp.download]]
    sha256 = "1cfd62d94ebe19a30521c457b839cd67f9cf8aec157b90e8dcbe6a4f58a2be1f"
    url = "https://github.com/JuliaBinaryWrappers/llama_cpp_jll.jl/releases/download/llama_cpp-v0.0.5+0/llama_cpp.v0.0.5.aarch64-linux-gnu-cxx11.tar.gz"
[[llama_cpp]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "84f151091c4bb94289261c3470ffa3aa9bf7c1df"
libc = "musl"
os = "linux"

    [[llama_cpp.download]]
    sha256 = "b1b81eaf1883cd3ea47d1dbc34149549581e6fea45fa5792f39537ecdeae47d1"
    url = "https://github.com/JuliaBinaryWrappers/llama_cpp_jll.jl/releases/download/llama_cpp-v0.0.5+0/llama_cpp.v0.0.5.aarch64-linux-musl-cxx03.tar.gz"
[[llama_cpp]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9beff5cd8c64b4d4c465b5ea87390e821ce2829f"
libc = "musl"
os = "linux"

    [[llama_cpp.download]]
    sha256 = "bc2756e21b27d7b6a5628745abe2636d5b364c2994a57af61e56a4dd47c60014"
    url = "https://github.com/JuliaBinaryWrappers/llama_cpp_jll.jl/releases/download/llama_cpp-v0.0.5+0/llama_cpp.v0.0.5.aarch64-linux-musl-cxx11.tar.gz"
[[llama_cpp]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "70baa3d6404d28a6907bb92bb71a07993ac0a290"
libc = "glibc"
os = "linux"

    [[llama_cpp.download]]
    sha256 = "eeb053b50c583a325cb59516baad31625b67e99cc682d0e3b10ca0aacf26ad90"
    url = "https://github.com/JuliaBinaryWrappers/llama_cpp_jll.jl/releases/download/llama_cpp-v0.0.5+0/llama_cpp.v0.0.5.i686-linux-gnu-cxx03.tar.gz"
[[llama_cpp]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "07ed6c65da30044c5bdb6c95173a8f2c83e050f8"
libc = "glibc"
os = "linux"

    [[llama_cpp.download]]
    sha256 = "8e9411b90a2fda5dd0f8bac5d47eb540c5219fd8266b5525366d2342c28cee4b"
    url = "https://github.com/JuliaBinaryWrappers/llama_cpp_jll.jl/releases/download/llama_cpp-v0.0.5+0/llama_cpp.v0.0.5.i686-linux-gnu-cxx11.tar.gz"
[[llama_cpp]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a92e7848b20a91c55b8e9a2bd31e272ba97a6d6c"
libc = "musl"
os = "linux"

    [[llama_cpp.download]]
    sha256 = "a59b6621adf987fb00be2fb86819d28b23069a0d86bce16c4d4a05f37bbefd09"
    url = "https://github.com/JuliaBinaryWrappers/llama_cpp_jll.jl/releases/download/llama_cpp-v0.0.5+0/llama_cpp.v0.0.5.i686-linux-musl-cxx03.tar.gz"
[[llama_cpp]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "611d70b27406f19fc3f8b5ab3964267942786867"
libc = "musl"
os = "linux"

    [[llama_cpp.download]]
    sha256 = "9b78e929ee030ab5bf3a8175c9b294df32f63d41432b20fa2d51fd836a8f0b9d"
    url = "https://github.com/JuliaBinaryWrappers/llama_cpp_jll.jl/releases/download/llama_cpp-v0.0.5+0/llama_cpp.v0.0.5.i686-linux-musl-cxx11.tar.gz"
[[llama_cpp]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "56581ff77a6c7ad6625962fc424596d9030e18be"
os = "windows"

    [[llama_cpp.download]]
    sha256 = "3ccc671d577c683540136db2c732a5d7e383bb062918229f72eceb8f66083f0f"
    url = "https://github.com/JuliaBinaryWrappers/llama_cpp_jll.jl/releases/download/llama_cpp-v0.0.5+0/llama_cpp.v0.0.5.i686-w64-mingw32-cxx03.tar.gz"
[[llama_cpp]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b6a71f28364ce5b28c7bfd0b4d95e7b1f19af07a"
os = "windows"

    [[llama_cpp.download]]
    sha256 = "d9ed893cea62cdc7578bb76fe22439ee25c31fc8b9c1ab97b39a99f4432daccb"
    url = "https://github.com/JuliaBinaryWrappers/llama_cpp_jll.jl/releases/download/llama_cpp-v0.0.5+0/llama_cpp.v0.0.5.i686-w64-mingw32-cxx11.tar.gz"
[[llama_cpp]]
arch = "x86_64"
git-tree-sha1 = "b1debb0b3491bf974e30d2ddda4f04a38cc29149"
os = "macos"

    [[llama_cpp.download]]
    sha256 = "06ae67870e1926eeed5ac2129402b2bebe4721d09da9cb7c30f1c4fa1d27e7d2"
    url = "https://github.com/JuliaBinaryWrappers/llama_cpp_jll.jl/releases/download/llama_cpp-v0.0.5+0/llama_cpp.v0.0.5.x86_64-apple-darwin.tar.gz"
[[llama_cpp]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "cff5030022a49f696f9674559f86341e35f8bcd3"
libc = "glibc"
os = "linux"

    [[llama_cpp.download]]
    sha256 = "ee3b93f084387fab0853fc7c7ffc3b81d6a87c0a13b5dc1c0c7ff95ba8a850be"
    url = "https://github.com/JuliaBinaryWrappers/llama_cpp_jll.jl/releases/download/llama_cpp-v0.0.5+0/llama_cpp.v0.0.5.x86_64-linux-gnu-cxx03.tar.gz"
[[llama_cpp]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b15b08dca476da1dfae13ec71f3a90fed07444be"
libc = "glibc"
os = "linux"

    [[llama_cpp.download]]
    sha256 = "68e4800d218cfc5eef0528040532695ec1ae5f420aa862b70ffa9807aeb4609f"
    url = "https://github.com/JuliaBinaryWrappers/llama_cpp_jll.jl/releases/download/llama_cpp-v0.0.5+0/llama_cpp.v0.0.5.x86_64-linux-gnu-cxx11.tar.gz"
[[llama_cpp]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "73574e82627a29079fe8c57075cd0041ae3bee62"
libc = "musl"
os = "linux"

    [[llama_cpp.download]]
    sha256 = "93d355462e71b6117b998e7afce535602fc8b9fe75e7a35b7b26801cbd0d9ac4"
    url = "https://github.com/JuliaBinaryWrappers/llama_cpp_jll.jl/releases/download/llama_cpp-v0.0.5+0/llama_cpp.v0.0.5.x86_64-linux-musl-cxx03.tar.gz"
[[llama_cpp]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c2f1ad3d6c30050326aaa4f298b87ac4005ea8c3"
libc = "musl"
os = "linux"

    [[llama_cpp.download]]
    sha256 = "139ef3434033f0f853f70af48dc9a82d6500719465983547df248e0cea051607"
    url = "https://github.com/JuliaBinaryWrappers/llama_cpp_jll.jl/releases/download/llama_cpp-v0.0.5+0/llama_cpp.v0.0.5.x86_64-linux-musl-cxx11.tar.gz"
[[llama_cpp]]
arch = "x86_64"
git-tree-sha1 = "15b99d352e1b6b35c5ecb2705e3c0af8784707ad"
os = "freebsd"

    [[llama_cpp.download]]
    sha256 = "275310002a69ab42dc436ff286bd87c0a858f5a45d6acbd960a319ba6fd9c945"
    url = "https://github.com/JuliaBinaryWrappers/llama_cpp_jll.jl/releases/download/llama_cpp-v0.0.5+0/llama_cpp.v0.0.5.x86_64-unknown-freebsd.tar.gz"
[[llama_cpp]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "55223fc0e9dc355a2cc3d02eef525f6648c6fdd9"
os = "windows"

    [[llama_cpp.download]]
    sha256 = "fe6110621181ba0d31c0d00aeac739f7bac34df925a0dbb4719210dbbc36947c"
    url = "https://github.com/JuliaBinaryWrappers/llama_cpp_jll.jl/releases/download/llama_cpp-v0.0.5+0/llama_cpp.v0.0.5.x86_64-w64-mingw32-cxx03.tar.gz"
[[llama_cpp]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f9ffb9157e5b8843af068a4f3f75ae93283bbdc2"
os = "windows"

    [[llama_cpp.download]]
    sha256 = "716fadd31aee7c60e90701e5d876baf5eb7207e87f55dc1411e444b12fab7069"
    url = "https://github.com/JuliaBinaryWrappers/llama_cpp_jll.jl/releases/download/llama_cpp-v0.0.5+0/llama_cpp.v0.0.5.x86_64-w64-mingw32-cxx11.tar.gz"
