# Autogenerated wrapper script for llama_cpp_jll for i686-w64-mingw32-cxx03
export embedding, libllama, main, perplexity, quantize

JLLWrappers.@generate_wrapper_header("llama_cpp")
JLLWrappers.@declare_library_product(libllama, "libllama.dll")
JLLWrappers.@declare_executable_product(embedding)
JLLWrappers.@declare_executable_product(main)
JLLWrappers.@declare_executable_product(perplexity)
JLLWrappers.@declare_executable_product(quantize)
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        libllama,
        "bin\\libllama.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_executable_product(
        embedding,
        "bin\\embedding.exe",
    )

    JLLWrappers.@init_executable_product(
        main,
        "bin\\main.exe",
    )

    JLLWrappers.@init_executable_product(
        perplexity,
        "bin\\perplexity.exe",
    )

    JLLWrappers.@init_executable_product(
        quantize,
        "bin\\quantize.exe",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
