# Autogenerated wrapper script for llama_cpp_jll for x86_64-w64-mingw32-cxx11
export baby_llama, benchmark, embedding, libllama, main, perplexity, q8dot, quantize, quantize_stats, save_load_state, vdot

JLLWrappers.@generate_wrapper_header("llama_cpp")
JLLWrappers.@declare_library_product(libllama, "libllama.dll")
JLLWrappers.@declare_executable_product(baby_llama)
JLLWrappers.@declare_executable_product(benchmark)
JLLWrappers.@declare_executable_product(embedding)
JLLWrappers.@declare_executable_product(main)
JLLWrappers.@declare_executable_product(perplexity)
JLLWrappers.@declare_executable_product(q8dot)
JLLWrappers.@declare_executable_product(quantize)
JLLWrappers.@declare_executable_product(quantize_stats)
JLLWrappers.@declare_executable_product(save_load_state)
JLLWrappers.@declare_executable_product(vdot)
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        libllama,
        "bin\\libllama.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_executable_product(
        baby_llama,
        "bin\\baby-llama.exe",
    )

    JLLWrappers.@init_executable_product(
        benchmark,
        "bin\\benchmark.exe",
    )

    JLLWrappers.@init_executable_product(
        embedding,
        "bin\\embedding.exe",
    )

    JLLWrappers.@init_executable_product(
        main,
        "bin\\main.exe",
    )

    JLLWrappers.@init_executable_product(
        perplexity,
        "bin\\perplexity.exe",
    )

    JLLWrappers.@init_executable_product(
        q8dot,
        "bin\\q8dot.exe",
    )

    JLLWrappers.@init_executable_product(
        quantize,
        "bin\\quantize.exe",
    )

    JLLWrappers.@init_executable_product(
        quantize_stats,
        "bin\\quantize-stats.exe",
    )

    JLLWrappers.@init_executable_product(
        save_load_state,
        "bin\\save-load-state.exe",
    )

    JLLWrappers.@init_executable_product(
        vdot,
        "bin\\vdot.exe",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
